### ISSUE TITLE
io.read is blocking mode? How to rightly use getscrlc etc function ?

### ISSUE THREAD

**Issue by suxiaojack** [philanc/plterm#3]
The function getcode use io.read(1) to get one char from stdin stream,but this would block thread processing?
For example, use term.getscrlc().
If not in raw mode,this must hand type key Enter to continue to get the return code?
If in raw mode , this would returned immediately,but get all nil value?

Waiting for your answer, thank you very much!

**Comment by suxiaojack** [comment]
---Ugly solution:
-----------------------
local term = require "plterm"
local mode = term.savemode()
function s(v)
 if v==nil then return "nil" end
 return tostring(v) 
end
term.setrawmode()
_stdout =io.stdout
io.stdout = io.stderr
local l,c = term.getscrlc()
io.stdout = _stdout
term.restoremode(mode)
print(s(l).."|"..s(c))

**Comment by philanc** [comment]
I don't understand your issue or your question.
if I do 
```
pt = require("plterm")
pt.setrawmode(); print(pt.getscrlc()); pt.setsanemode()
```
It does display `24     80` which are the expected dimensions of my xterm.
Does it work for you?

**Comment by suxiaojack** [comment]
Yes! Thanks!
I mean, If only wrote like local l,c = pt.getcrlc(). it's block the thread,then waiting for human to press Enter key .
Use stty -g
I found  my terminal setting has problem , under default config opened terminal has
4500:5:bf:8a3b:3:1c:7f:15:4:0:1:0:11:13:1a:0:12:f:17:16:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
after setsanemode is
2102:5:bf:8a3b:3:1c:7f:15:4:0:1:0:11:13:1a:0:12:f:17:16:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0

**Comment by philanc** [comment]
Yes, TTY I/O is by default in blocking mode. It is possible to set it non blocking but this is more complex and cannot be done in pure Lua.

If you are only interested in getting the terminal size, on Linux you can use `stty size`. For example:
```
function term_size()
	local fh = io.popen("stty size")
	local out = fh:read("*a")
	local succ, e, msg = fh:close()
	if not succ then return nil, e, msg end
	local lines, cols = out:match("(%d+)%s+(%d+)")
	if not cols then return nil, "stty size: cannot parse output" end
	lines = tonumber(lines)
	cols = tonumber(cols)
	return lines, cols
end
```

No need to change the terminal mode.
