### ISSUE TITLE
thanks, rewrite term.lua with CC0 license?

### ISSUE THREAD

**Issue by vitiral** [philanc/plterm#4]
Hey and thanks so much for the great library!

I adapted your `term` implementation slightly to write my first text editor ([ele][1]).

I've taken the work to re-write it for the Civboot.org project: https://github.com/civboot/civlua/blob/main/civix/civix/term.lua

The rewrite was _almost_ entirely new code. I used your original code as a reference. I also based the structure of `niceinputs()` on your code, but as you see my approach is almost entirely different.

I _believe_ the rewrite is sufficient rework to relicense it as CC0/UNLICENSE (community commons), but I wanted to check with you first.

Also, I thought you might like to see the modifications made. I took the original `inputs` and made it output `strlen>1` for all "complex" (non-character) outputs ('return', 'esc', 'f1', etc). This made writing my editor much more readable as I didn't have to convert between integer codes all over the place :smile: 

I also created the `Term` object. In my editor I create a `FakeTerm` with the same API. This lets me write unit tests without disturbing the terminal, which is super nice.

You might also appreciate my approach to utf8 stream decoding.

I plan on better documenting all of the above, possibly releasing `utf8stream` and `term` as libraries on luarocks. Would you be interested in co-maintaining them?

[1]: http://github.com/civboot/ele

**Comment by vitiral** [comment]
Note: even if it were CC0, I would keep the attribution to you. However, it would mean that others wouldn't need to attribute you to use pieces (or even the entire file).

**Comment by philanc** [comment]
> thanks so much for the great library!

You're welcome!

> I adapted your term implementation slightly to write my first text editor [ele]

I will certainly look into it. 

> relicense it as CC0/UNLICENSE 

I will keep my own project MIT-licensed (I think it is simple and nice - it is also the license used for Lua itself and a large part if not most of the code contributed by the Lua community).  But if you want to CC0-license your civix/term.lua code, I am perfectly fine with it. Thanks for asking.

> I plan on better documenting all of the, possibly releasing utf8stream and term as libraries on luarocks. Would you 
be interested in co-maintaining them?

I am afraid I don't have enough time/bandwidth to do this.

> even if it were CC0, I would keep the attribution to you. 

That is nice. I appreciate it.

**Comment by vitiral** [comment]
Awesome, thanks so much!

**Comment by vitiral** [comment]
And I wasn't suggesting you relicense your code, just that I relicense
civix/term.lua entirely.


Thanks!

**Comment by vitiral** [comment]
I see now that the title was misleading though. I updated it.
